spring.application.name=ReachGRC-Trust--B
spring.security.user.name=admin
spring.security.user.password=admin

google.sheets.credentials-path=credentials.json
google.sheets.application-name=ReachGRC-Trust
